In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from pprint import pprint
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,confusion_matrix

data=load_iris()
df=pd.DataFrame(data.data,columns=data.feature_names)
df['Class']=data.target_names[data.target]
pprint(df.head())
print('\n')

x=df.iloc[:,:-1].values
y=df.Class.values
print(x[:5])
print(y[:5])
print('\n')

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)


knn_classifier=KNeighborsClassifier(n_neighbors=5)
knn_classifier.fit(x_train,y_train)

predictions=knn_classifier.predict(x_test)
print(predictions)
print('\n')


print("Training Accuracy Score :\n ",accuracy_score(y_train,knn_classifier.predict(x_train)))
print("Testing Accuracy Score \n ",accuracy_score(y_test,knn_classifier.predict(x_test)))
print("Training Confusion Matrix \n",confusion_matrix(y_train,knn_classifier.predict(x_train)))
print("Test Confusion Matrix \n",confusion_matrix(y_test,knn_classifier.predict(x_test)))

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

    Class  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa  


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
['setosa' 'setosa' 'setosa' 'setosa' 'setosa']


['virginica' 'versicolor' 'versicolor' 'versicolor' 'setosa' 'virginica'
 'virginica' 'versicolor' 'virginica' 'versicolor' 'setosa' 'versicolor'
 'virginica' 'setosa' 'setosa' 'versicolor' 'setosa' 'setosa' 'versicolor'
 'versicolor' 'setosa' 'virginica' 'setosa' 'versicolor' 'virginica'
 'versicolor' 'v

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdim